[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "perla-extract"
version = "0.0.5"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Sherjeel Shabih", email = "sherjeel.shabih@hu-berlin.de" },
    { name = "Pepe Marquez", email = "jose.marquez@physik.hu-berlin.de" },
    { name = "Kevin Jablonka", email = "mail@kjablonka.com" },
    { name = "Sharat Patil", email = "sharat.patil@physik.hu-berlin.de" },
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]


dependencies = [
    "pydantic",
    "litellm<=1.82.6",
    "diskcache",
    "pymupdf",
    "deepdiff>=8.1.0",
    "munkres",
    "pint",
    "numpy",
    "levenshtein",
    "instructor",
    "fire",
    "flatdict==4.0.0",
    "mip",
    "loguru",
    "pandas",
    "feedparser",
    "pdf2doi>=1.7"
]

[tool.uv.extra-build-dependencies]
flatdict = ["setuptools<82.0.0"]

[project.optional-dependencies]
dev = ["jupyter", "docformatter", "pytest", "ruff", "bump-my-version"]
nougat = ["nougat"]
marker = ["marker-pdf"]
pymupdf = ['pymupdf']
cache = ["redis"]

docs = [
    "mkdocs-material>=9.4.0",
    "mkdocstrings[python]>=0.22.0",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-literate-nav>=0.6.0",
    "fire"
]

[project.scripts]
perla-extract = "perla_extract.pipeline:main_cli"

[tool.setuptools.package-data]
"perla_extract" = ["allowed_journals.csv", "data/extractions/claude-opus-4-1-20250805/*.json", "data/extractions/claude-opus-4-20250514/*.json", "data/extractions/claude-sonnet-4-20250514/*.json", "data/extractions/gpt-4.1-2025-04-14/*.json", "data/extractions/gpt-4o-2024-08-06/*.json", "data/extractions/gpt-5-2025-08-07/*.json", "data/extractions/gpt-5-mini-2025-08-07/*.json", "data/extractions/humans/*/*.json", "data/ground_truth/dev/*.json", "data/ground_truth/test/*.json", "papersbot/feeds.txt"]
