parameters:
  pce:
    units: "%"
  jsc:
    units: "mA cm^-2"
  voc:
    units: "V"
  ff:
    units: ""

tolerances:
  pce: 0.1 # %
  jsc: 0.1 # mA cm^-2
  voc: 0.01 # V
  ff: 0.1 # %

layer_fields:
  name: "Name"
  functionality: "Functionality"
  thickness: "Thickness"
  deposition: "Deposition Method"
