import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import re


def parse_stats_file(content: str) -> pd.DataFrame:
    """
    Parses the stats log file content into a pandas DataFrame.

    Args:
        content: A string containing the log file data.

    Returns:
        A pandas DataFrame with metrics for each run, indexed by date.
    """
    # Split the file into separate runs based on the star separator
    runs = content.strip().split(
        "************************************************************\n************************************************************"
    )

    parsed_runs = []

    # A mapping from section headers to a prefix for column names
    section_prefixes = {
        "Getting abstracts": "Abstracts",
        "Strict REGEX against abstract": "Regex",
        "Checking unpaywall for pdfs": "PDFs",
    }

    for run_text in runs:
        if not run_text.strip():
            continue

        run_data = {}

        # Find the primary date for the run
        date_match = re.search(r"Run: (\d{4}-\d{2}-\d{2})", run_text)
        if not date_match:
            continue
        run_data["date"] = pd.to_datetime(date_match.group(1))

        # The first section has no header, we'll call it "Initial"
        sections = re.split(r"\n([A-Za-z ]+ Run:)", run_text)

        # Process the initial (unnamed) section
        initial_section = sections[0]
        for line in initial_section.strip().split("\n"):
            if "CEST" in line:
                continue
            match = re.match(r"([^:]+):\s*(\d+)", line)
            if match:
                key, value = match.groups()
                # Sanitize key and add prefix
                col_name = f"Papersbot - {key.strip()}"
                run_data[col_name] = int(value)

        # Process subsequent, named sections
        for i in range(1, len(sections), 2):
            header = sections[i].replace("Run:", "").strip()
            body = sections[i + 1]
            prefix = section_prefixes.get(header, "Unknown")

            for line in body.strip().split("\n"):
                if "CEST" in line:
                    continue
                match = re.match(r"([^:]+):\s*(\d+)", line)
                if match:
                    key, value = match.groups()
                    col_name = f"{prefix} - {key.strip()}"
                    run_data[col_name] = int(value)

        parsed_runs.append(run_data)

    df = pd.DataFrame(parsed_runs).set_index("date")
    return df


def plot_trends(df: pd.DataFrame):
    """
    Generates and displays 2x2 trend charts from the parsed data.

    Args:
        df: The DataFrame generated by parse_stats_file.
    """
    fig, axes = plt.subplots(2, 2, figsize=(16, 12), sharex=True)
    fig.suptitle("Processing Trends Over Time", fontsize=20)

    # --- Plot 1: Initial Processing ---
    ax1 = axes[0, 0]
    # df[['Papersbot - Total number of papers processed', 'Papersbot - Number of relevant papers', 'Papersbot - Number of papers matched']].plot(ax=ax1, marker='o')
    df[
        [
            "Papersbot - Number of relevant papers",
            "Papersbot - Number of papers matched",
        ]
    ].plot(ax=ax1, marker="o")
    ax1.set_title("Initial Paper Processing", fontsize=14)
    ax1.set_ylabel("Count")
    ax1.grid(True, linestyle="--", alpha=0.6)
    ax1.legend()

    # --- Plot 2: Abstract Retrieval ---
    ax2 = axes[0, 1]
    df[
        [
            "Abstracts - Total number of papers processed",
            "Abstracts - Number of abstracts found",
            "Abstracts - Number of papers with metadata",
        ]
    ].plot(ax=ax2, marker="o")
    ax2.set_title("Abstract Retrieval Stage", fontsize=14)
    ax2.set_ylabel("Count")
    ax2.grid(True, linestyle="--", alpha=0.6)
    ax2.legend()

    # --- Plot 3: REGEX Filtering ---
    ax3 = axes[1, 0]
    df[
        ["Regex - Total number of papers processed", "Regex - Number of papers matched"]
    ].plot(ax=ax3, marker="o")
    ax3.set_title("Strict REGEX Filtering Stage", fontsize=14)
    ax3.set_xlabel("Date")
    ax3.set_ylabel("Count")
    ax3.grid(True, linestyle="--", alpha=0.6)
    ax3.legend()

    # --- Plot 4: PDF Downloading ---
    ax4 = axes[1, 1]
    df[
        [
            "PDFs - Total number of papers processed",
            "PDFs - Number of pdfs found",
            "PDFs - Number of papers with no Pdfs",
        ]
    ].plot(ax=ax4, marker="o")
    ax4.set_title("Unpaywall PDF Search", fontsize=14)
    ax4.set_xlabel("Date")
    ax4.set_ylabel("Count")
    ax4.grid(True, linestyle="--", alpha=0.6)
    ax4.legend()

    # Format the x-axis to show dates clearly
    for ax in axes.flat:
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
        plt.setp(ax.get_xticklabels(), rotation=30, ha="right")

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()


def plot_trends_stck_bar(df: pd.DataFrame):
    """
    Generates and displays 2x2 trend charts from the parsed data.

    Args:
        df: The DataFrame generated by parse_stats_file.
    """
    fig, axes = plt.subplots(2, 2, figsize=(16, 12), sharex=True)
    fig.suptitle("Processing Trends Over Time", fontsize=20)

    # --- Plot 1: Initial Processing ---
    ax1 = axes[0, 0]
    # df[['Papersbot - Total number of papers processed', 'Papersbot - Number of relevant papers', 'Papersbot - Number of papers matched']].plot(ax=ax1, marker='o')
    df[["Papersbot - Number of papers matched"]].plot(ax=ax1, kind="bar", stacked=False)
    ax1.set_title("Papersbot (Relaxed REGEX)", fontsize=14)
    ax1.set_ylabel("Count")
    ax1.set_xlabel("Date")
    ax1.legend(["# Papers matched"], loc="upper left")
    ax1_2 = ax1.twinx()
    ax1_2.plot(df[["Papersbot - Number of relevant papers"]].values, "g")
    # ax1_2.set_ylabel(color='g')
    ax1_2.tick_params(axis="y", labelcolor="g")
    ax1_2.legend(["# New papers"], loc="upper right")
    ax1.grid(True, linestyle="--", alpha=0.6)

    # --- Plot 2: Abstract Retrieval ---
    ax2 = axes[0, 1]
    # df[['Papersbot - Number of papers matched','Abstracts - Total number of papers processed', 'Abstracts - Number of papers with metadata', 'Abstracts - Number of abstracts found']].plot(ax=ax2, kind='bar', stacked=False)
    df[
        [
            "Abstracts - Total number of papers processed",
            "Abstracts - Number of papers with metadata",
            "Abstracts - Number of abstracts found",
        ]
    ].plot(ax=ax2, kind="bar", stacked=False)
    ax2.set_title("Abstract Retrieval Stage", fontsize=14)
    ax2.set_ylabel("Count")
    ax2.set_xlabel("Date")
    ax2.grid(True, linestyle="--", alpha=0.6)
    ax2.legend(["# Total processed", "# With metadata", "# Abstracts found"])

    # --- Plot 3: REGEX Filtering ---
    ax3 = axes[1, 0]
    # df[['Papersbot - Number of papers matched','Abstracts - Number of papers with metadata','Regex - Total number of papers processed', 'Regex - Number of papers matched']].plot(ax=ax3,kind='bar', stacked=False)
    df[
        ["Regex - Total number of papers processed", "Regex - Number of papers matched"]
    ].plot(ax=ax3, kind="bar", stacked=False)
    ax3.set_title("Strict REGEX Filtering Stage", fontsize=14)
    ax3.set_xlabel("Date")
    ax3.set_ylabel("Count")
    ax3.grid(True, linestyle="--", alpha=0.6)
    ax3.legend(["# Total processed", "# Papers matched"])

    # --- Plot 4: PDF Downloading ---
    ax4 = axes[1, 1]
    # df[[ 'Regex - Number of papers matched','PDFs - Total number of papers processed', 'PDFs - Number of papers with no Pdfs', 'PDFs - Number of pdfs found']].plot(ax=ax4, kind='bar', stacked=False)
    df[
        [
            "PDFs - Total number of papers processed",
            "PDFs - Number of papers with no Pdfs",
            "PDFs - Number of papers with errors",
            "PDFs - Number of pdfs found",
        ]
    ].plot(ax=ax4, kind="bar", stacked=False)
    ax4.set_title("Unpaywall PDF Search", fontsize=14)
    ax4.set_xlabel("Date")
    ax4.set_ylabel("Count")
    ax4.grid(True, linestyle="--", alpha=0.6)
    ax4.legend(["# Total processed", "# With no PDFs", "# With errors", "# PDFs found"])

    # Format the x-axis to show dates clearly
    for ax in axes.flat:
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
        ax.set_xticks(range(len(df.index)), df.index.strftime("%Y-%m-%d"))
        plt.setp(ax.get_xticklabels(), rotation=30, ha="right")
        # plt.setp(ax, rotation=30, ha='right')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()


# --- Main execution ---
if __name__ == "__main__":
    # In a real script, you would load from a file like this:

    with open("runs/stats.txt", "r") as f:
        file_content = f.read()

    # Parse the data from the provided string

    stats_df = parse_stats_file(file_content)
    stats_df.to_csv("stats_df.csv")
    # Print the resulting DataFrame to check correctness
    print("--- Parsed Data DataFrame ---")
    print(stats_df)
    print(stats_df.columns)
    print("\nGenerating charts...")

    # Generate and display the plots
    plot_trends_stck_bar(stats_df.iloc[1:])
