# This workflow is named "Daily Python Pipeline"
name: Daily Python Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow every day at midnight UTC.
  schedule:
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TQDM_DISABLE: 1
  NOMAD_URL: ${{ vars.NOMAD_URL }}
  NOMAD_USERNAME: ${{ vars.NOMAD_USERNAME }}
  NOMAD_PASSWORD: ${{ secrets.NOMAD_PASSWORD }}
  NOMAD_STATS_ID: ${{ vars.NOMAD_STATS_ID }}
  UNPAYWALL_EMAIL: ${{ vars.OA_EMAIL }}
  UPLOAD_ID: ${{ vars.UPLOAD_ID }}
  LLM_MODEL_NAME: ${{ vars.LLM_MODEL_NAME }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_API_TOKEN }}
  OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-pipeline"
  run-pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Step 2: Sets up a Python 3.11 environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install uv, the fast Python installer
      - name: Install uv
        run: pip install uv
      
      # Step 4: Install project dependencies
      - name: Install dependencies with uv
        run: uv pip install --system .
     
      # Step 5: Download PapersBot run
      - name: Download PapersBot run stats from Nomad
        run: python -u src/perla_extract/papersbot/nomad_utils.py download
      
      # Step 6: Run PapersBot pipeline
      - name: Run PapersBot pipeline
        run: perla-extract papersbot ./downloaded_papers
      
      # Step 7: Run extraction pipeline and upload to Nomad
      - name: Run extraction pipeline
        run: perla-extract extract ./downloaded_papers --model_name $LLM_MODEL_NAME --nomad --nomad_upload_id $UPLOAD_ID
      
      # Step 8: Upload PapersBot run
      - name: Upload PapersBot runs to Nomad
        run: python -u src/perla_extract/papersbot/nomad_utils.py upload 
